name: monorepo_case_study
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

workspace:
  - packages/core
  - packages/data
  - packages/domain

dependencies:
  auto_route: ^11.1.0
  bloc: ^9.2.0
  domain: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.1.0
  intl: ^0.20.2

dev_dependencies:
  auto_route_generator: ^10.5.0
  bloc_test: ^10.0.0
  build_runner: ^2.11.0
  freezed: ^3.2.5
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
