name: domain
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  freezed_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^2.11.1
  freezed: ^3.2.5
  very_good_analysis: ^10.0.0

